### ISSUE TITLE
Mirror plugins site of std update sites

### ISSUE THREAD

**Issue by cforce** [junoyoon/simpleupdatesiterepo#1]
Howto create a mirror (e.G if http://jenkins.mirror.isppower.de/updates/update-center.json) site with ur plugin. We have an lan internal jenkins server with no direct web access. We already mirrorred the whole folder http://updates.jenkins-ci.org/download/plugins/ to a local webserver which is accessibble by our jenkins.

We tried to run yout tool to create the update-center.json but it does not recognize the regular plugins update site strcuture which is \plugin name\version\file.hip below update site,
You tool only reads hpi files in plugins folder itself. Then i can't write a update-center.json with several version.

Can u please add this feature. 
tx!

**Comment by junoyoon** [comment]
Sorry.. This plugin does not target to your situation. What about making your each jenkins instance points your mirror site? You can configure it in "Manage Hudson" menu.

**Comment by cforce** [comment]
Sorry, i dond't understand. Mirroing isn't the problem, but the index file created does not match . I Searched and replace the org index file for "http://updates.jenkins-ci.org/download/" and chnaged it to our mirror site. The i changed the update site  here: https://jenijns.srv/jenkins/pluginManager/advanced tp poit to our index file. If i select plugin an click install, jenkins still seems to try to download from http://updates.jenkins-ci.org/download/.

**Comment by junoyoon** [comment]
Right.. Jenkins tries to download plugins from the location written in json 
See... http://ftp-nyc.osuosl.org/pub/jenkins/updates/update-center.json

all you have to do is create your own version of json which download field points your mirror. 
And make each Jenkins instance see modified json.

**Comment by cforce** [comment]
Eaxctly that is what i did, but it doesn't wok!
Jenkins is trying downloading from original jekins plugins update site (http://updates.jenkins-ci.org/download/), although i configured our own json file in update settings and that is reachable and downloadbale from our jenkins server running web browser. All links in josn link to our server and also the hpi files can be downloaded. We are using trunk vcersion of jenkins server. We filed a bug a long time ago.

**Comment by cforce** [comment]
I assuem that jenkins internally ignores the json update file configured via settings and uses its own update center instead.

**Comment by cforce** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-11598

The problem is that the md5 checksum, for the josn file does not match. because in just search and replace uris .

<div class=error><img src='/jenkins/static/94dbdb64/images/none.gif' height=16 width=1>Digest mismatch: Q+ejIVBw/42JwLVOxctt7TC38cw= vs jccSvBIyYEZqMMXc2xms5J+jo5E= in update center &#039;default&#039;</div>


The cause seems to be jenkins useses default uris/json for download.

**Comment by junoyoon** [comment]
Well.. It doesn't work that way as far as I know. Could you send me your json and the screenshot of Jenkins management page? I can help you.

My email is junoyoon at gmail dot com

**Comment by junoyoon** [comment]
That's right... I've just forgot it.. update site json protects its content using md5 stuff..

You can try to point to the custom update site using my simpleupdatesiteplugin instead.(After deleting current updatesite). It doens't check md5 stuff..

**Comment by cforce** [comment]
Yes, your plugin does this fine, but it does not scan classic multi level plugin folder structure to create json from that.
For you plugin all hpi files have to exist in the root folder (flat), but the jenkins update site keeps its plugins in folfder strcuture limke \plugin name\version\file.hpi .
Can you add an option to your plugin to nscan for hpi files down the root folder?

Tx a lot for help!

**Comment by junoyoon** [comment]
What i mean was to use plugin not repo generation stuff.  Well the easiest way might be just to delete md5 stuff from Jenkins core. What version of Jenkins are you using?

**Comment by cforce** [comment]
Urgs, i really don't want to patch core lib.
But if i undertand you correctly, your plugin provides a a second json configuretion form which uses ur plugin update method which doesn't check for md5?
Yo if i isnatll your plugin i can use it with my own josn file which does not have proper md5 to update from jenkins plugins update mirror?

**Comment by junoyoon** [comment]
Yes. That's right

**Comment by cforce** [comment]
It does not work. I configured my update site json in ur plugin (also a suppport and rss url which works both as expected)

The update checker says - no updates - although i get 10 upates displayed on jenkins regular plugin update screen alspo with my json configured) I checked manually in my json and found hpi with hiher version as locally installed.

**Comment by junoyoon** [comment]
You're right.. I've just tested my plugin against official json file. I found out it doesn't work.
I'll investigated the cause of problem in the coming week.

**Comment by junoyoon** [comment]
Ah... you should modify some json attribute.

"id":"default"
==>
"id : "simpleupdatesite"

Try it.

**Comment by cforce** [comment]
You mean i shall replace the string "id":"default" with "id : "simpleupdatesite" in my modified plugins update site json file?

**Comment by cforce** [comment]
I replaced the 

"id":"default"
with
"id : "simpleupdatesite"

Now i see error message on Jenkins Plugin updates  Panel

"Incorrect contents on Update Site (https://server.in/jenkins/userContent/update-center.json)
- Please fix it in Jenkins configuration"

**Comment by cforce** [comment]
somebody alive?
